export const PROJECTS = [
  // Tab 0: GenAI & Multi-Agent Systems
  [
    {
      title: "Strands GenAI Automation for Snowflake",
      desc: "Architected a GenAI-driven automation system using Strands Agents SDK for Snowflake denormalized view generation. Designed and implemented multi-agent orchestration with GitHub, Transformation, Execution, and Snowflake Agents. Integrated GitHub MCP and Snowflake MCP to enable secure, modular, and dynamic agent execution. Automated complex SQL generation and execution workflows, reducing manual effort and improving data reliability.",
      img: "/images/projects/strands-genai.svg",
      alt: "Strands GenAI Automation System Architecture",
      link: "https://github.com/nikhiltammi/",
      demoLink: "#",
      techStack: [
        "AWS Bedrock",
        "Strands Agents SDK",
        "Snowflake MCP",
        "GitHub MCP",
        "Python",
        "Multi-Agent Orchestration",
      ],
      category: "Enterprise GenAI Platform",
      features: [
        "Multi-agent workflow orchestration",
        "GitHub MCP integration for version control",
        "Snowflake MCP for database operations",
        "Automated SQL generation and validation",
        "Dynamic agent execution pipeline",
        "Enterprise-grade security controls",
      ],
      achievements: [
        "Reduced manual SQL development effort by 70%",
        "Automated end-to-end view generation pipeline",
        "Enabled non-technical users to generate reports",
      ],
      duration: "4 months",
      status: "Production",
    },
    {
      title: "Enterprise GenAI Financial Chatbot",
      desc: "Developed an enterprise GenAI financial chatbot generating optimized SQL scripts for natural-language prompts, enhancing data retrieval by 30% and supporting 10+ visualization formats. Implemented using Amazon Bedrock and LangGraph for conversational agent orchestration, accelerating agent workflows by 40%. Delivered a non-hallucinating, guardrail-enforced conversational engine with streaming responses and <15s average latency.",
      img: "/images/projects/financial-chatbot.svg",
      alt: "GenAI Financial Chatbot Interface",
      link: "https://github.com/nikhiltammi/",
      demoLink: "#",
      techStack: [
        "AWS Bedrock",
        "Bedrock AgentCore",
        "LangGraph",
        "Strands SDK",
        "Redshift MCP",
        "Python",
        "Active Directory",
      ],
      category: "Enterprise AI Application",
      features: [
        "Natural language to SQL conversion",
        "10+ visualization format support",
        "Streaming response delivery",
        "Fine-grained access controls for 500+ users",
        "Guardrail-enforced responses",
        "Role-based data access via Active Directory",
      ],
      achievements: [
        "30% improvement in data retrieval efficiency",
        "<15s latency for complex SQL queries",
        "50% improvement in system scalability",
        "100+ internal users validated MVP",
      ],
      duration: "9 months",
      status: "Production",
    },
    {
      title: "Test Case Automation using AWS Bedrock",
      desc: "Designed a GenAI-driven automation framework leveraging AWS Bedrock and multi-agent collaboration to generate and execute test cases. Enhanced testing efficiency by automating validation processes, reducing manual effort, and improving software reliability through intelligent test generation.",
      img: "/images/projects/test-automation.svg",
      alt: "Test Case Automation Framework",
      link: "https://github.com/nikhiltammi/",
      demoLink: "#",
      techStack: [
        "AWS Bedrock",
        "Multi-Agent Systems",
        "Python",
        "Pytest",
        "CI/CD Integration",
      ],
      category: "DevOps Automation",
      features: [
        "Automated test case generation from requirements",
        "Multi-agent collaboration for test coverage",
        "Integration with CI/CD pipelines",
        "Intelligent test prioritization",
        "Regression test automation",
      ],
      achievements: [
        "Reduced manual test writing effort by 60%",
        "Improved test coverage by 40%",
        "Faster bug detection in CI/CD pipeline",
      ],
      duration: "3 months",
      status: "Completed",
    },
  ],
  // Tab 1: Cloud & DevOps Projects
  [
    {
      title: "AI-Powered Export Compliance Platform",
      desc: "Designed and implemented an AI-powered export document delivery platform for Boeing, migrating 150+ file formats to AWS while improving regulatory compliance efficiency by 30%. Led the large-scale migration of 7+ million files from on-prem systems to Amazon S3, preserving 100% ACL fidelity through precise permission and entitlement mapping.",
      img: "/images/projects/compliance-platform.svg",
      alt: "Export Compliance Platform Architecture",
      link: "https://github.com/nikhiltammi/",
      demoLink: "#",
      techStack: [
        "AWS S3",
        "Amazon Kendra",
        "Amazon Bedrock",
        "IAM",
        "CloudWatch",
        "Lambda",
        "Python",
      ],
      category: "Enterprise Cloud Platform",
      features: [
        "Smart Search with Amazon Kendra + Bedrock",
        "Persona-based application layer (admin, reviewer, end user)",
        "End-to-end audit logging and traceability",
        "Role-based access controls",
        "Automated file classification pipeline",
        "Export control compliance enforcement",
      ],
      achievements: [
        "7M+ files migrated with 100% ACL fidelity",
        "30% improvement in compliance efficiency",
        "150+ file formats supported",
        "Enterprise-scale high availability",
      ],
      duration: "Ongoing",
      status: "Production",
    },
    {
      title: "CI/CD Pipeline Optimization",
      desc: "Optimized large-scale CI/CD pipelines at SEIU 775 by refactoring 36 standalone CloudFormation stacks into nested stacks, reducing template size from ~950 KB to ~300 KB and cutting deployment time from ~3 hours to ~1.5 hours. Redesigned artifact handling in CodePipeline for improved stability.",
      img: "/images/projects/cicd-optimization.svg",
      alt: "CI/CD Pipeline Architecture",
      link: "https://github.com/nikhiltammi/",
      demoLink: "#",
      techStack: [
        "AWS CloudFormation",
        "CodePipeline",
        "S3",
        "Bytebase",
        "Jenkins",
        "GitHub Actions",
      ],
      category: "DevOps Engineering",
      features: [
        "Nested CloudFormation stack architecture",
        "Optimized artifact handling via S3",
        "Database CI/CD automation with Bytebase",
        "Production schema deployment under 1 minute",
        "Template size reduction by 68%",
      ],
      achievements: [
        "50% reduction in deployment time",
        "68% reduction in template size",
        "Schema deployment: 3-4 hours to <1 minute",
        "Improved pipeline stability",
      ],
      duration: "6 months",
      status: "Production",
    },
    {
      title: "GitLab CI/CD Migration to AWS EKS",
      desc: "Led migration of enterprise GitLab CI/CD infrastructure from OCI OKE to AWS EKS at SS&C Technologies, modernizing pipelines supporting 300+ servers across four environments. Reduced CI/CD compute costs by ~60% through dynamic scaling with Karpenter, Fargate, and Graviton EC2.",
      img: "/images/projects/eks-migration.svg",
      alt: "EKS Migration Architecture",
      link: "https://github.com/nikhiltammi/",
      demoLink: "#",
      techStack: [
        "AWS EKS",
        "Karpenter",
        "Fargate",
        "Graviton EC2",
        "GitLab CI",
        "CDK",
        "Docker",
      ],
      category: "Infrastructure Migration",
      features: [
        "Dynamic, on-demand compute scaling",
        "Hybrid GitLab runner architecture",
        "Drift detection with CDK validation",
        "GDPR and NIST compliance checks",
        "Docker-in-Docker support",
      ],
      achievements: [
        "60% reduction in CI/CD compute costs",
        "300+ servers modernized",
        "4 environments supported",
        "Improved deployment reliability",
      ],
      duration: "12 months",
      status: "Completed",
    },
  ],
  // Tab 2: Data Engineering & ML
  [
    {
      title: "Oracle to AWS Glue Migration Platform",
      desc: "Designed an agent-orchestrated modernization platform to convert Oracle PL/SQL into AWS Glue Java jobs, enabling automated extraction, conversion, validation, deployment, and execution through a single workflow. Applied GenAI-assisted validation and automation to data transformation workflows.",
      img: "/images/projects/oracle-migration.svg",
      alt: "Oracle to AWS Glue Migration Platform",
      link: "https://github.com/nikhiltammi/",
      demoLink: "#",
      techStack: [
        "AWS Glue",
        "Oracle PL/SQL",
        "Java",
        "GenAI",
        "Multi-Agent Systems",
        "Python",
      ],
      category: "Data Modernization",
      features: [
        "Automated PL/SQL to Glue conversion",
        "Multi-agent orchestrated workflow",
        "GenAI-assisted code validation",
        "End-to-end deployment automation",
        "Consistent, safe execution pipelines",
      ],
      achievements: [
        "Reduced manual migration effort by 80%",
        "Automated validation and testing",
        "Single workflow for complete migration",
      ],
      duration: "5 months",
      status: "Production",
    },
    {
      title: "Real-Time Data Ingestion Framework",
      desc: "Built a real-time data ingestion framework using Amazon Kinesis, S3, and Redshift at M-Digital Tech, supporting high-throughput log processing and downstream analytics. Architected cloud-native ML pipelines using AWS ECS, Lambda, and S3.",
      img: "/images/projects/data-ingestion.svg",
      alt: "Real-Time Data Ingestion Architecture",
      link: "https://github.com/nikhiltammi/",
      demoLink: "#",
      techStack: [
        "Amazon Kinesis",
        "S3",
        "Redshift",
        "AWS ECS",
        "Lambda",
        "Python",
        "Docker",
      ],
      category: "Data Engineering",
      features: [
        "High-throughput log processing",
        "Scalable ML training pipelines",
        "Containerized Python models",
        "Real-time streaming analytics",
        "Fault-tolerant data workflows",
      ],
      achievements: [
        "Enabled real-time analytics",
        "Scalable training and inference",
        "High availability data pipelines",
      ],
      duration: "6 months",
      status: "Completed",
    },
    {
      title: "GenAI Model and RAG Evaluator",
      desc: "Implemented a GenAI-powered system on AWS Bedrock to evaluate RAG models, enhancing model selection and system scalability. Optimized RAG model evaluation by synthesizing file summaries and output analysis, securing optimal performance with AWS integration.",
      img: "/images/projects/rag-evaluator.svg",
      alt: "RAG Model Evaluator Dashboard",
      link: "https://github.com/nikhiltammi/",
      demoLink: "#",
      techStack: [
        "AWS Bedrock",
        "RAG",
        "Python",
        "Vector Databases",
        "LangChain",
        "Evaluation Frameworks",
      ],
      category: "ML Platform",
      features: [
        "Automated RAG model evaluation",
        "File summary synthesis",
        "Performance benchmarking",
        "Model comparison metrics",
        "Scalable evaluation pipelines",
      ],
      achievements: [
        "Optimized model selection process",
        "Reduced evaluation time by 50%",
        "Improved RAG accuracy metrics",
      ],
      duration: "2 months",
      status: "Completed",
    },
  ],
  // Tab 3: Infrastructure & Automation
  [
    {
      title: "Modular AWS Infrastructure with Terraform",
      desc: "Designed and deployed modular AWS infrastructure using Terraform and Ansible at M-Digital Tech, provisioning 10+ VPC components (VPCs, subnets, EC2, IAM roles, security groups) to support scalable ML environments across multiple stages.",
      img: "/images/projects/terraform-infra.svg",
      alt: "Terraform Infrastructure Architecture",
      link: "https://github.com/nikhiltammi/",
      demoLink: "#",
      techStack: [
        "Terraform",
        "Ansible",
        "AWS VPC",
        "EC2",
        "IAM",
        "Security Groups",
      ],
      category: "Infrastructure as Code",
      features: [
        "Multi-stage environment support (dev/test/prod)",
        "Modular VPC components",
        "Automated security group configuration",
        "IAM role provisioning",
        "Reproducible infrastructure",
      ],
      achievements: [
        "10+ VPC components automated",
        "Consistent multi-stage deployments",
        "Reduced provisioning time by 70%",
      ],
      duration: "4 months",
      status: "Completed",
    },
    {
      title: "Kubernetes Microservices Platform",
      desc: "Managed microservices deployments using Kubernetes Helm charts at M-Digital Tech, enabling zero-downtime releases, versioned rollbacks, and consistent configuration across 10+ services. Integrated SonarQube SAST into CI/CD pipelines.",
      img: "/images/projects/kubernetes-platform.svg",
      alt: "Kubernetes Microservices Platform",
      link: "https://github.com/nikhiltammi/",
      demoLink: "#",
      techStack: [
        "Kubernetes",
        "Helm",
        "Docker",
        "SonarQube",
        "Jenkins",
        "AWS EKS",
      ],
      category: "Platform Engineering",
      features: [
        "Zero-downtime deployments",
        "Versioned rollback capability",
        "Consistent configuration management",
        "Automated SAST scanning",
        "Cross-region disaster recovery",
      ],
      achievements: [
        "10+ microservices managed",
        "100% code commit scanning",
        "Zero-downtime release process",
      ],
      duration: "8 months",
      status: "Completed",
    },
    {
      title: "Chat with CI/CD Pipelines",
      desc: "Developed an AWS Bedrock and GenAI-enhanced chat system to streamline CI/CD processes, boosting deployment efficiency. Refined CI/CD event handling with dynamic insights and tailored recommendations, improving overall pipeline management quality.",
      img: "/images/projects/cicd-chat.svg",
      alt: "CI/CD Chat Interface",
      link: "https://github.com/nikhiltammi/",
      demoLink: "#",
      techStack: [
        "AWS Bedrock",
        "GenAI",
        "CI/CD",
        "Python",
        "REST APIs",
        "WebSockets",
      ],
      category: "DevOps AI Tool",
      features: [
        "Natural language CI/CD queries",
        "Dynamic pipeline insights",
        "Tailored deployment recommendations",
        "Real-time event handling",
        "Pipeline health monitoring",
      ],
      achievements: [
        "Improved deployment efficiency",
        "Reduced troubleshooting time",
        "Enhanced pipeline visibility",
      ],
      duration: "2 months",
      status: "Completed",
    },
  ],
];
